leftnav:
- identifier: 2354f691-c344-3414-8013-73c49d1944e8
  name: Syllabus
  url: /pages/syllabus/
  weight: 10
- identifier: d54ec244-9b96-389a-e4e4-be50d2e06c64
  name: Course Expectations
  parent: 2354f691-c344-3414-8013-73c49d1944e8
  url: /pages/syllabus/course-expectations
  weight: 20
- identifier: 2cb6e376-84cf-9ec6-bdf2-066c1411f3f2
  name: Calendar
  url: /pages/calendar
  weight: 30
- identifier: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  name: Instructor Insights
  url: /pages/instructor-insights/
  weight: 40
- identifier: 2364f2ee-45d9-3648-eaf6-a1c5265391dc
  name: Course Goals and Measuring Success
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/course-goals-and-measuring-success
  weight: 50
- identifier: 7f3566e3-50e6-d8ac-1998-bc145b7b5121
  name: Pre-course Activities
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/pre-course-activities
  weight: 60
- identifier: 20597891-b286-88ee-357b-da6fdba1d86e
  name: Collaboration with Partner Organizations
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/collaboration-with-partner-organizations
  weight: 70
- identifier: 01b61425-8619-596a-c333-24796b9e4e49
  name: Pre-trip Deliverables
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/pre-trip-deliverables
  weight: 80
- identifier: e702a1f5-1b29-364d-5e70-ac34ffea7063
  name: Post-trip Work
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/post-trip-work
  weight: 90
- identifier: e7144194-7217-3f8e-4991-6a06d77ad9a6
  name: Evolution of the Course
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/evolution-of-the-course
  weight: 100
- identifier: d74125d9-2238-a20c-d484-c453b721c3ce
  name: Reflections and Advice
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/reflections-and-advice
  weight: 110
- identifier: cad09ac0-4718-423b-a9fa-221959f7b04a
  name: Applications Beyond the Course
  parent: c7dc5b7f-248d-ae6b-71d8-d564ab3927e5
  url: /pages/instructor-insights/applications-beyond-the-course
  weight: 120
- identifier: 1601f42d-e42f-e62f-c909-bc0f6e6bdd73
  name: Readings
  url: /pages/readings
  weight: 130
- identifier: 3682febb-c6a8-5c41-3d0a-fb78b4019874
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 140
- identifier: a3b128d8-e8d1-84e7-f370-f97e36e8b3ba
  name: Assignments
  url: /pages/assignments/
  weight: 150
- identifier: 564190aa-addb-75cb-a44f-633498ae2eb9
  name: Deliverables and Action Steps
  parent: a3b128d8-e8d1-84e7-f370-f97e36e8b3ba
  url: /pages/assignments/deliverables-and-action-steps
  weight: 160
- identifier: 3818c9e7-1d22-9879-8b06-b951bb3fadcf
  name: Projects
  url: /pages/projects/
  weight: 170
- identifier: dbdb449f-9aea-f745-4b10-c97c28a45f1b
  name: Unjani Clinic
  parent: 3818c9e7-1d22-9879-8b06-b951bb3fadcf
  url: /pages/projects/unjani-clinic
  weight: 180
- identifier: a9073ed2-5726-e216-9189-c7ea6b4e466e
  name: L V Prasad Eye Institute
  parent: 3818c9e7-1d22-9879-8b06-b951bb3fadcf
  url: /pages/projects/l-v-prasad-eye-institute
  weight: 190
